# Exibição do conteúdo das variáveis...
print ("Nome completo:")
MyName = input()
print("Altura:")
MyHeight = float(input())
print('Idade:')
MinhaIdade = int(input())
print('Data de nascimento:')
MinhaDataDeNascimento = input()
print('Nacionalidade:')
MeuPaisPreferido = input()
print('cor dos olhos:')
CorDosMeusOlhos = input()
print('Time do coração:')
TimeQueTorço = input()